apiVersion: v1
kind: Service
metadata:
  name: userdefined-api-srv
spec:
  type: NodePort
  selector:
    app: userdefined-api
  ports:
    - 
      name: userdefined-api
      port: 80
      protocol: TCP
      targetPort: 80


